name: Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
    paths-ignore:
            - '.github/**'
            - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
     - '.github/**'
     - 'README.md'
  
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1'] #,'1.7','nightly']
        julia-arch: [x64]
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install Libcbf in accessible spot"
        # Note that this is fragile in that it assumes the libhdf5 package name
        run: |
            apt-get download libcbf1; dpkg-deb -x libcbf1* extralibs
            apt-get download libhdf5-103; dpkg-deb -x libhdf5* extralibs
            pushd extralibs/usr/lib/x86_64-linux-gnu
            ln -s libcbf.so.1 libcbf.so
            popd
            pushd 
      - uses: julia-actions/julia-buildpkg@latest
      - name: "Add local libcbf to shared library path"
        run: |
            echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/extralibs/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
      - name: "Check"
        run: |
             env
      - uses: julia-actions/julia-runtest@latest
        with:
          coverage: 'false'
